### ISSUE TITLE
Non-English crashes

### ISSUE THREAD

**Issue by mperham** [mperham/kuiq#5]
It seems when you have a data binding based on the label text, Kuiq will crash because the model has a "next_retry" method but it does not have the corresponding method name for other languages. How do we map an attribute with a dynamic label?

```
text_column(t("Next Retry"))
```

**Comment by AndyObtiva** [comment]
I fixed that here:
https://github.com/mperham/kuiq/pull/6/files

I simply inverse-translated the translated column name inside the model, and then invoked the English method name.

**Comment by AndyObtiva** [comment]
Another way of handling this is to specify a manual mapping of table column names to model attributes.

For example, instead of data-binding the table cell rows this way:

```ruby
table {
  text_column('name')
  text_column('email')

  cell_rows <=> [user, :contacts]
}
```

It would be data-bound this way instead:

```ruby
table {
  text_column(t('name'))
  text_column(t('email'))

  cell_rows <=> [user, :contacts, 
                              column_attributes: {
                                t('name') => :name,
                                t('email') => :email,
                              }
                           ]
}
```

Now, regardless of what translation the table columns have, the data-binding will still map them to the English-named model attribute methods.

**Comment by mperham** [comment]
I don't particularly like the inverse translation hack we're currently using. The second approach feels better. It's more verbose but it's explicit and easy to understand. Less magic. 🚫🪄

**Comment by mperham** [comment]
I'm trying to use your data binding code but getting this error:

```ruby
        cell_rows <=> [job_manager.process_set, :lazy, column_attributes: {
                t("Name") => :identity,
                t("Started") => :started_at,
                t("RSS") => :rss,
                t("Threads") => :concurrency,
                t("Busy") => :busy
              }]
```

```
/Users/mperham/.gem/ruby/3.2.0/gems/glimmer-2.7.3/lib/glimmer/data_binding/observable_model.rb:100:in `property_observer_list': undefined method `to_sym' for [:identity, :started_at, :rss, :concurrency, :busy]:Array (NoMethodError)

        property_key = property_name&.to_sym
                                    ^^^^^^^^
Did you mean?  to_s
               to_set
	from /Users/mperham/.gem/ruby/3.2.0/gems/glimmer-2.7.3/lib/glimmer/data_binding/observable_model.rb:88:in `has_observer?'
	from /Users/mperham/.gem/ruby/3.2.0/gems/glimmer-2.7.3/lib/glimmer/data_binding/observable_model.rb:55:in `add_observer'
	from /Users/mperham/.gem/ruby/3.2.0/gems/glimmer-2.7.3/lib/glimmer/data_binding/observer.rb:100:in `observe'
	from /Users/mperham/.gem/ruby/3.2.0/gems/glimmer-dsl-libui-0.11.4/lib/glimmer/libui/control_proxy/table_proxy.rb:248:in `block in data_bind_read'
	from /Users/mperham/.gem/ruby/3.2.0/gems/glimmer-2.7.3/lib/glimmer/data_binding/observer.rb:45:in `call'
	from /Users/mperham/.gem/ruby/3.2.0/gems/glimmer-dsl-libui-0.11.4/lib/glimmer/libui/control_proxy/table_proxy.rb:256:in `data_bind_read'
	from /Users/mperham/.gem/ruby/3.2.0/gems/glimmer-dsl-libui-0.11.4/lib/glimmer/libui/data_bindable.rb:35:in `data_bind'
	from /Users/mperham/.gem/ruby/3.2.0/gems/glimmer-dsl-libui-0.11.4/lib/glimmer/dsl/libui/data_binding_expression.rb:40:in `interpret'
	from /Users/mperham/.gem/ruby/3.2.0/gems/glimmer-2.7.3/lib/glimmer/dsl/engine.rb:217:in `block in interpret_expression'
```

**Comment by AndyObtiva** [comment]
I agree. I was planning to refactor the code eventually to utilize the manual configuration approach, but we are using a new advanced feature that enables table implicit data-binding to a lazy enumerable for lazy loading (without using <= or <=>). The table control does not support using a lazy enumerable in explicit data-binding with <= and <=> yet. I was planning to use this opportunity to add support for that to Glimmer DSL for LibUI to enable configuring column_attributes. Hopefully, I will get to that this weekend.
